version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.0.3
    restart: always
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
      #  - db_data:/var/lib/mysql
      - ./docker/mysqldata:/var/lib/mysql
      - ./docker/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
networks:
  back:
volumes:
  db_data: